name: Scan vulnerabilities

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Scan Go vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Python image
        run: docker pull python:3.9-alpine

      - name: Pull Trivy image
        run: docker pull aquasec/trivy:0.57.0

      - name: Run Trivy vulnerability scanner
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.cache:/root/.cache aquasec/trivy:0.57.0 image python:3.9-alpine --exit-code 1 --format json --ignore-unfixed --severity CRITICAL,HIGH --scanners vuln > trivy_report.json

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:


