name: Trivy Local Image Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-local-image:latest .

      - name: Run Trivy Scan
        run: |
          trivy image --severity HIGH,CRITICAL --ignore-unfixed --exit-code 1 my-local-image:latest





