name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master

      - name: Run Trivy Scan
        run: |
          trivy image --severity HIGH,CRITICAL --ignore-unfixed python:3.4-alpine






