name: Scan vulnerabilities

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Scan Go vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Python image
        run: docker pull python:3.4-alpine

      - name: Pull Trivy image
        run: docker pull aquasec/trivy:0.57.0

      - name: Run Trivy vulnerability scanner and create GitHub issues
        uses: knqyf263/trivy-issue-action@v0.0.6
        with:
          assignee: knqyf263
          severity: CRITICAL
          skip-dirs: integration,examples,pkg
          label: kind/security
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_IMAGE: aquasec/trivy:0.57.0
          TRIVY_IMAGE_SCAN: python:3.4-alpine
